---
# see: http://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_ports_cdh5.html

allowed_local_tcp_ports:
  - "8020:8090"
  # for Syndicate-REST
  - 38888
  - "9000:9001"
  - 13562
  - 19888
  - 10020
  - "30000:49999"
  - "50010:50495"

allowed_ip_ranges:
  - "172.17.0.0/16"
