---
# syndicate-ms/defaults/main.yml

# Syndicate-ms Defaults

syndicatems_prereq_packages:
  - apt-transport-https
  - ca-certificates
  - unzip
  - make
  - daemon

syndicate_user: syndicate
syndicate_password: syndicate

gae_path: "/home/{{syndicate_user}}/google_appengine"
gae_cmd: "dev_appserver.py --admin_host=0.0.0.0 --host=0.0.0.0 --storage_path=/home/syndicate/datastore --skip_sdk_update_check=true /usr/src/syndicate/ms"

datastore_path: "/home/{{ syndicate_user }}/datastore"
ms_path: "/usr/src/syndicate/ms"

# Download defaults
dl_dir: /opt/downloads

GAE_SDK: https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.36.zip



