---
# Acquisition Gateway cat test
# Description: Create an AG that initializes with 3 files as it's data set, create a UG to cat the data, and confirm accuracy

- name: setup_ag_cat
  type: setup
  tmpdirs:
    - name: 004_ag_cat
      varname: config_dir
  randnames:
    - test_volume
    - test_ag
    - put_ug
    - cat_ug
  seqloop:              # list from of ints from 0
    - name: cacheloop
      quantity: 2
  valueloop:            # list/dict with the name(s) and value(s) defined below
    - name: randfile
      values:
        - name: local_file1
          value: /tmp/syndicate-AG-dataset/local_file1
        - name: local_file2
          value: /tmp/syndicate-AG-dataset/local_file2
        - name: local_file3
          value: /tmp/syndicate-AG-dataset/local_file3
  vars:
    - name: syndicate_conf
      value: $config_dir/syndicate.conf
    - name: ag_driver
      value: $SYNDICATE_PYTHON_ROOT/syndicate/ag/drivers/disk
    - name: ag_path
      value: $SYNDICATE_AG_ROOT/syndicate-ag
    - name: put_path
      value: $SYNDICATE_UG_ROOT/syndicate-put
    - name: cat_path
      value: $SYNDICATE_UG_ROOT/syndicate-cat
  debug: off

- name: create ag dataset
  type: sequential
  tasks:
    - name: make an AG dataset area/path #the path is defined by the AG, e.g. /tmp/syndicate-AG-dataset
      command: $tasksf_dir/mkagdataset.py $ag_driver --no-secrets None #mkagdataset.py <driver path> <--secrets|--no-secrets> <gateway privkey pem> 

- name: create local files
  type: sequential
  loop_on: randfile
  tasks:
    - name: make random files in the AG dataset path 
      command: $tasksf_dir/mkrandfile.py $randfile.value 16384

- name: config
  type: sequential
  tasks:
    - name: setup security config
      command: $SYNDICATE_TOOL --trust_public_key -c "$syndicate_conf" --debug setup "$SYNDICATE_ADMIN" "$SYNDICATE_PRIVKEY_PATH" "$SYNDICATE_MS"

    - name: add test volume config
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_volume name=$test_volume description="test volume" blocksize=1024 email=$SYNDICATE_ADMIN

    - name: create AG config
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_ag type=AG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update AG config
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_ag caps=ALL port=31112 driver=$ag_driver

- name: daemon AG
  type: daemon
  tasks:
    - name: start AG
      command: $ag_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_ag
      sleep: 20
      exit: 0

- name: setup UGs
  type: sequential
  tasks:
    - name: create cat UG config
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$cat_ug type=UG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update cat UG config
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$cat_ug caps=ALL

- name: run ag cat tests
  type: sequential
  loop_on: randfile
  tasks:
    - name: test cat
      loop_on: cacheloop #nested loop, cache first iteration
      command: $cat_path -d2 -f -c "$syndicate_conf" -u $SYNDICATE_ADMIN -v $test_volume -g $cat_ug /${randfile.name}
      checkout: ${randfile.value}
