---

- name: setup_write_read_fs
  type: setup
  tmpdirs:
    - name: 052_write_read_fs
      varname: config_dir
    - name: 052_write_read_fs_mount
      varname: mount_dir
  randnames:
    - test_volume
    - test_rg
    - test_ug
  valueloop:
    - name: test_fsizes
      values:
        - 0
        - 1
        - 4095
        - 4096
        - 4097
        - 8191
        - 8192
        - 8193
        - 16384
        - 65535
        - 65536
        - 65537
  vars:
    - name: local_file
      value: $config_dir/local_file
    - name: syndicate_conf
      value: $config_dir/syndicate.conf
    - name: rg_driver
      value: $SYNDICATE_PYTHON_ROOT/syndicate/rg/drivers/disk
    - name: rg_path
      value: $SYNDICATE_RG_ROOT/syndicate-rg
    - name: ug_path
      value: $SYNDICATE_UG_ROOT/syndicatefs

- name: config
  type: sequential
  tasks:
    - name: setup
      command: $SYNDICATE_TOOL --trust_public_key -c "$syndicate_conf" --debug setup "$SYNDICATE_ADMIN" "$SYNDICATE_PRIVKEY_PATH" "$SYNDICATE_MS"

    - name: add test volume
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_volume name=$test_volume description="test volume" blocksize=4096 email=$SYNDICATE_ADMIN

    - name: create RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_rg type=RG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update RG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_rg caps=ALL port=31112 driver=$rg_driver

    - name: create UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" create_gateway name=$test_ug type=UG volume=$test_volume email=$SYNDICATE_ADMIN private_key=auto port=31111

    - name: update UG
      command: $SYNDICATE_TOOL -c "$syndicate_conf" update_gateway name=$test_ug caps=ALL

- name: daemon UG/RG
  type: daemon
  tasks:
    - name: start RG
      command: $rg_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_rg
      exit: 0

    - name: start UG
      command: $ug_path -c "$syndicate_conf" -d2 -f -u $SYNDICATE_ADMIN -v $test_volume -g $test_ug $mount_dir
      exit: 0

- name: check syndicate is mounted
  type: sequential
  tasks:
    - name: wait for syndicatefs to be mounted
      command: sleep 5s

    - name: test filesystem type
      command: stat -f -L -c %T $mount_dir
      compareout: "fuseblk"

- name: run write/read tests with files in different sizes
  type: sequential
  loop_on: test_fsizes
  tasks:
    - name: make local_file
      command: $tasksf_dir/mkrandfile.py ${local_file}_${loop_var} $loop_var

    - name: copy local_file to syndicate_volume
      command: cp ${local_file}_${loop_var} ${mount_dir}/${loop_var}

    - name: compare
      command: diff -q ${local_file}_${loop_var} ${mount_dir}/${loop_var}
      exit: 0
