---
# create users on the system

- name: load userlist
  hosts: all
  become: yes
  tasks:
    - name: Include user variables
      include_vars: vars/users.yml

- name: provision users
  hosts: all
  become: yes
  roles:
    - provision-users

