---

- name: Add key for jenkins-debian-glue apt repo
  apt_key:
    data: "{{ lookup('file','jenkins.grml.org.key') }}"
    state: present

- name: Add jenkins-debian-glue apt repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://jenkins.grml.org/debian jenkins-debian-glue-release main"
    - "deb-src http://jenkins.grml.org/debian jenkins-debian-glue-release main"

- name: Install packages for jenkins-debian-glue
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: installed
  with_items:
  - jenkins-debian-glue
  - git-buildpackage
  - subversion-tools
  - cowbuilder
  - reprepro

- name: Add jenkins to sudoers for specific tools
  copy:
    src: "jenkins_sudo"
    dest: "/etc/sudoers.d/jenkins_sudo"
    mode: 0440
    owner: root
    group: root

- name: Configure jenkins-debian-glue
  template:
    src: "debian_glue.j2"
    dest: "/etc/jenkins/debian_glue"
    mode: 0644
    owner: root
    group: root

- name: Copy over gpg signing public key for inter-build trust
  copy:
    src: "{{ site_name }}_pub.gpg"
    mode: 0644
    owner: root
    group: root
    dest: "{{ item }}"
  with_items:
    - "/etc/jenkins/{{ site_name }}_pub.gpg"
    - "{{ apache_sites_dir }}/{{ site_name }}/{{ csr_name }}_pub.gpg"

# may also need to create /srv/repositories or j-d-g will have trouble
- name: Create web accessible repository directory for artifacts
  file:
    dest: "{{ apache_sites_dir }}/{{ site_name }}/repos"
    state: directory
    mode: 0755
    owner: jenkins
    group: jenkins

- name: create basic index.html file with instructions for use of site
  become: no
  local_action:
    command pandoc -s -f markdown -t html5 -o {{ role_path }}/files/index.html {{ role_path }}/files/index.md

- name: copy over index.html file
  copy:
    src: "index.html"
    dest: "{{ apache_sites_dir }}/{{ site_name }}/index.html"
    mode: 0644
    owner: root
    group: root
